# Generated by Django 4.2 on 2024-03-20 12:34

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=blogs.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
