# Generated by Django 4.2 on 2024-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isCreator',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
