# Generated by Django 4.2 on 2024-03-28 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_iscreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imageUrl',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
