# Generated by Django 4.2 on 2024-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='compareUniversities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
