# Generated by Django 4.2 on 2024-03-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_photo_customuser_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imageUrl',
            field=models.ImageField(default='images/defaultAvatar.png', upload_to='images/'),
        ),
    ]
