# Generated by Django 4.2 on 2024-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_compareuniversities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isModerator',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
