# Generated by Django 4.2 on 2024-03-28 20:08

from django.db import migrations, models
import universities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.CharField(default=universities.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('universityName', models.CharField(blank=True)),
                ('img', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('accreditationLevel', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(blank=True)),
                ('reviews', models.JSONField(blank=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('features', models.TextField(blank=True)),
                ('remoteEducation', models.CharField(blank=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('specialties', models.JSONField(blank=True)),
                ('contactInfo', models.JSONField(blank=True)),
                ('website', models.CharField(blank=True)),
            ],
        ),
    ]
