# Generated by Django 4.2 on 2024-03-21 11:24

from django.db import migrations, models
import universities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.CharField(default=universities.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('universityName', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('accreditationLevel', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('reviews', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('features', models.TextField()),
                ('remote_education', models.CharField()),
                ('price', models.CharField(max_length=100)),
                ('specialties', models.JSONField()),
                ('contactInfo', models.JSONField()),
                ('website', models.URLField()),
            ],
        ),
    ]
