# Generated by Django 4.2 on 2024-03-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='reviews',
        ),
    ]
