# Generated by Django 4.2 on 2024-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_remove_university_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='reviewCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
