# Generated by Django 4.2 on 2024-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_rename_remote_education_university_remoteeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='img',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='universityName',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.CharField(),
        ),
    ]
