# Generated by Django 4.2 on 2024-04-03 13:43

from django.db import migrations, models
import universities.models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_reviewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUniversity',
            fields=[
                ('id', models.CharField(default=universities.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('place', models.IntegerField()),
                ('universityName', models.CharField()),
                ('img', models.TextField(max_length=500)),
                ('applicationsNumber', models.IntegerField()),
                ('budgetApplications', models.IntegerField()),
                ('averageCompetitveScore', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
